# Site settings
title: ドーンライト合同会社
company: ドーンライト合同会社
email: dawnlightrealty@gmail.com
address: "〒150-0043 東京都渋谷区道玄坂1丁目10番8号渋谷道玄坂東急ビル2F-C"
description: 【公式】ドーンライト合同会社
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dawnlight.jp" # the base hostname & protocol for your site

linkedin_username: shihwensu
twitter_username: shihwensu
github_username: flyakite

# Build settings
markdown: kramdown
