# Site settings
title: ドーンライト合同会社
email: dawnlightrealty@gmail.com
description: 【公式】ドーンライト合同会社
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dawnlight.jp" # the base hostname & protocol for your site

twitter_username: shihwensu
github_username: flyakite

# Build settings
markdown: kramdown
